# -*- coding: utf-8 -*-
"""
HTML 模板渲染

将 BacktestRecord 指标面板和 plotly 图表嵌入到统一的 HTML 壳子中。
"""

from __future__ import annotations

from common.formatting import format_pct, format_float
from data.models import BacktestRecord


def render_html(bt: BacktestRecord, plotly_div: str) -> str:
    """渲染完整 HTML 报告

    Args:
        bt: 回测记录
        plotly_div: plotly Figure.to_html() 的输出

    Returns:
        完整 HTML 字符串
    """
    return _TEMPLATE.format(
        title=f"回测报告 #{bt.id} — {bt.symbol} / {bt.strategy}",
        metrics=_render_metrics(bt),
        plotly_div=plotly_div,
    )


def _render_metrics(bt: BacktestRecord) -> str:
    """渲染指标卡片 HTML"""

    def card(label: str, value: str, color: str = '#333') -> str:
        return (
            f'<div class="card">'
            f'<div class="card-label">{label}</div>'
            f'<div class="card-value" style="color:{color}">{value}</div>'
            f'</div>'
        )

    total_return = format_pct(bt.total_return)
    return_color = '#28A745' if (bt.total_return or 0) >= 0 else '#DC3545'

    cards: list[str] = [
        card('总收益率', total_return, return_color),
        card('夏普比率', format_float(bt.sharpe_ratio), '#333'),
        card('最大回撤', format_pct(bt.max_drawdown), '#DC3545'),
        card('胜率', format_pct(bt.win_rate), '#333'),
        card('交易次数', str(bt.total_trades or 0), '#333'),
        card('年化收益', format_pct(getattr(bt, 'annual_return', None)), '#333'),
        card('初始资金', f"{bt.initial_capital or 0:,.0f}", '#333'),
        card('最终权益', f"{getattr(bt, 'end_balance', 0) or 0:,.0f}", '#333'),
    ]

    return '\n'.join(cards)


_TEMPLATE = """<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<style>
* {{ margin: 0; padding: 0; box-sizing: border-box; }}
body {{
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto,
                 "Helvetica Neue", Arial, "Noto Sans SC", sans-serif;
    background: #f5f6fa;
    color: #333;
    padding: 20px;
}}
.container {{
    max-width: 1200px;
    margin: 0 auto;
}}
.header {{
    text-align: center;
    padding: 24px 0 20px;
}}
.header h1 {{
    font-size: 24px;
    font-weight: 600;
    color: #1a1a2e;
}}
.metrics {{
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(140px, 1fr));
    gap: 12px;
    margin-bottom: 24px;
}}
.card {{
    background: #fff;
    border-radius: 8px;
    padding: 16px;
    text-align: center;
    box-shadow: 0 1px 3px rgba(0,0,0,0.08);
}}
.card-label {{
    font-size: 12px;
    color: #888;
    margin-bottom: 6px;
    text-transform: uppercase;
    letter-spacing: 0.5px;
}}
.card-value {{
    font-size: 22px;
    font-weight: 700;
}}
.chart {{
    background: #fff;
    border-radius: 8px;
    padding: 12px;
    box-shadow: 0 1px 3px rgba(0,0,0,0.08);
}}
.footer {{
    text-align: center;
    padding: 16px;
    font-size: 12px;
    color: #aaa;
}}
</style>
</head>
<body>
<div class="container">
    <div class="header">
        <h1>{title}</h1>
    </div>
    <div class="metrics">
        {metrics}
    </div>
    <div class="chart">
        {plotly_div}
    </div>
    <div class="footer">
        Generated by quant v0.2.0 &middot; Powered by Plotly
    </div>
</div>
</body>
</html>"""
